version: '3.8'

services:
  servidor_web:
    build: .
    container_name: contenedor_compose
    ports:
      - "9090:80"
    volumes:
      # Cambiamos el punto (.) por ./frontend para apuntar a tus archivos reales
      - ./frontend:/usr/share/nginx/html
